"""Builds bpdata.js (repo root): everything bpgen.js needs, as one JS constant.

    python tools/bp/build_bpdata.py

Contents:
  parts        placeable part types: prefab, hashes, settings struct, size, ports (canonical frame)
  orientations orientation code -> 3x3 rotation (world = R . local)
  schema       the game's own struct table, copied in order from its newest saved blueprint, so a
               generated file declares exactly what the game writes itself
  cable        the data cable prefab and its usual _type byte
  version      the .bpmeta _version the game currently writes
"""
import collections, glob, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bpformat, corpus
from hashes import ascii_hash64, part_hash

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))


def newest_game_blueprint():
    files = glob.glob(os.path.join(corpus.D, 'Blueprints', '*.bp'))
    files.sort(key=os.path.getmtime, reverse=True)
    for f in files:
        meta = f[:-3] + '.bpmeta'
        if os.path.exists(meta) and os.path.getsize(f) > 0:
            return f, json.load(open(meta, encoding='utf-8-sig'))
    raise SystemExit('no saved blueprint found')


def main():
    db = json.load(open(os.path.join(HERE, 'partdb.json'), encoding='utf-8'))
    schemas = json.load(open(os.path.join(HERE, 'schemas.json'), encoding='utf-8'))
    struct_name = {int(v['hash'], 16): k.split('+')[0] for k, v in schemas.items()}
    ori = json.load(open(os.path.join(HERE, 'orientations.json'), encoding='utf-8'))

    src, meta = newest_game_blueprint()
    schema, parts = bpformat.read(open(src, 'rb').read())
    field_names = {}
    for k, v in schemas.items():
        for name, off, size in v['fields']:
            field_names[ascii_hash64(name)] = name
    table = []
    for st in schema:
        name = struct_name.get(st['hash'])
        if name is None:
            name = f"?{st['hash']:016x}"
        table.append({'name': name, 'hash': f"{st['hash']:016x}", 'size': st['size'],
                      'fields': [[field_names.get(h, f'?{h:016x}'), f'{h:016x}', o, s] for h, o, s in st['fields']]})

    out_parts = {}
    for t, v in db.items():
        st = struct_name[int(v['schema_hash'], 16)]
        assert part_hash(v['prefab']) == int(v['hash'], 16)
        out_parts[t] = {'name': v['name'], 'prefab': v['prefab'], 'hash': v['hash'], 'mirrored_hash': v.get('mirrored_hash'),
                        'struct': st, 'size': v['size'],
                        'ports': {n: {'cell': p['cell'], 'dir': p['dir'], 'kind': 'data'} for n, p in v['ports'].items()}}

    # labels for the edge stubs (geometry from tools/bp/parts/structure.json): a plate whose text faces local +z
    # and whose back (local -z) must rest against a part
    structure = json.load(open(os.path.join(HERE, 'parts', 'structure.json'), encoding='utf-8'))
    for prefab, tid in (('SC_LabelSmall', 'label_small'), ('SC_LabelMedium', 'label_large')):
        e = structure[prefab]
        assert part_hash(prefab) == int(e['hash'], 16)
        out_parts[tid] = {'name': e['name'], 'prefab': prefab, 'hash': e['hash'], 'mirrored_hash': None,
                          'struct': 'EPC_SCLabel', 'size': e['size'], 'ports': {}, 'passive': True,
                          'max_chars': e['text']['max_chars']}

    # the data cable's usual _type byte (settings byte 2)
    types = collections.Counter()
    for f in glob.glob(os.path.join(corpus.D, 'Blueprints', '*.bp'))[:200]:
        _, ps = bpformat.read(open(f, 'rb').read())
        for p in ps:
            if p['part'] == corpus.CABLE:
                types[p['data'][21]] += 1
    cable = {'prefab': 'SC_DataCable', 'hash': f'{corpus.CABLE:016x}', 'struct': 'EPC_SCCable',
             'type_byte': types.most_common(1)[0][0] if types else 0}

    data = {'source_schema': os.path.basename(src), 'version': meta.get('_version', '1.0.212'),
            'parts': out_parts, 'orientations': {k: v['rotation'] for k, v in ori.items()},
            'schema': table, 'cable': cable}
    js = ('// Generated by tools/bp/build_bpdata.py from tools/bp/*.json and the newest saved blueprint. Do not edit.\n'
          'const BP_DATA = ' + json.dumps(data, separators=(',', ':')) + ';\n'
          "if (typeof module !== 'undefined') module.exports = BP_DATA;\n")
    with open(os.path.join(ROOT, 'bpdata.js'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(js)
    print(f'bpdata.js: {len(out_parts)} parts, {len(table)} schema structs from {os.path.basename(src)} '
          f"(version {data['version']}), cable _type {cable['type_byte']}, {len(js) // 1024} KB")


if __name__ == '__main__':
    main()
