"""Writes tools/bp/parts/controls_displays.md from controls_displays.json + cd_validation.json.

    python cd_make_md.py        (run after validate_controls_displays.py)
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(HERE, 'controls_displays.json'), encoding='utf-8'))
E = json.load(open(os.path.join(HERE, 'cd_validation.json'), encoding='utf-8'))

HEAD = r'''# Controls, displays, cameras and monitors: placement data

Output: `controls_displays.json` (keyed by simulator `type_id`, or by prefab name for parts the simulator lacks).
Built by `validate_controls_displays.py` (about 15 s), which also writes the evidence file `cd_validation.json`.
This page is generated by `cd_make_md.py`.

## Result in one paragraph
{SUMMARY}

## Method
Everything comes from game data. The corpus is used only to check it.

1. **Footprint.** The root `EPC_SC*` component of every part prefab (the `EPC_SpaceshipComponent` base) stores the part's
   bounding size in metres as a float3 at byte 12. Footprint = that box centred on the prefab origin, at 0.125 m per
   cell. Canonical frame = orientation 16, origin = the footprint's min corner, as in `model.py`.
2. **Port table.** The same component stores the electric ports as `i32 n` + n × `{f32 x, y, z; i32 facing; i32 type}`.
   - facing: 0 +x, 1 −x, 2 +y, 3 −y, 4 +z, 5 −z.
   - type: 0 data in, 1 data out, 2 power, 3 data both (wireless), 4 plasma, 5 universal (port frames).
   - The table order is the game's port order: Localization `SC_<key>_Port0..N` and the simulator's `TYPES[t].order`
     match it for every part here.
   - Positions equal the `Port ...` child nodes' `EPC_Renderer` positions, which are the centres of the face cells
     inside the part. Their euler rotations (Unity ZXY, the mesh's +z is outward) give the same facing as the table.
   - Port cell = face cell + facing. The table sits at a varying offset, so `cd_geom_ports.py` finds it by matching
     the node positions.
3. **Twins.** `"<prefab> M"` GameObjects exist in `globalgamemanagers.assets` for every part here except Colored Light
   and Small Toggleable Light. `cd_prefab_dump.py` dumps them, and for every part their port nodes are the
   x-reflection of the normal ones: dx → w−1−dx, with the x facing negated. `mirrored_ports` is read from the twin
   prefab itself.
4. **Struct.** The struct is the one the corpus records use. For parts with no corpus records it is the root class's
   own `+Blueprint+BlueprintData` (all five are in `schemas.json`).
   - Red Alert Light and Braking Point System use the base `EPC_SpaceshipComponent` struct (`_col` only).
   - Camera With Zoom and Rotational Telescopic Camera use `EPC_SCCamera`.
   - Field types come from `lib_burst_generated.pdb`: every `bool` and `byte` field is 1 byte, even where the schema
     declares 4.
5. **Method check.** The same code reproduces `partdb.json` exactly: all 43 logic parts, including size, port cells and
   port order, the 2-tall Data Hub and the Wireless Transmitter.

### Corpus validation (all 301 blueprints, all three cable kinds; `cd_corpus.py`, `cd_analysis.py`)
For every instance of a part or its twin, the instance is placed with `orientations.json` and min-corner anchoring,
then these are checked:
- **(a) Inside the footprint:** no cable cells, and no other part's box overlaps it. Curved frames and glass are
  reported apart, because their boxes are bigger than their real shape.
- **(b) Adjacent cables:** every cable cell next to the part that opens toward it must sit on a predicted port cell,
  with the inward direction matching (counted by cable kind). The check also counts direct port-to-port contacts. It
  walks each cable network to the far end to see what the port is wired to, and so whether it is an input or an
  output.
- **(c) Twins:** checked with their own (reflected) ports. The table lists them separately.
- **(d) Mount face:** the face that carries the `JointsArea` polygons should touch something (frame, glass, part or
  cable). This tests the height and anchoring in flipped orientations.
- **(e) End to end:** `check_json()` re-places every corpus instance using nothing but the JSON. It finds
  **3,206 cable hits on predicted port cells and 0 cables inside footprints**. The only cable ends that open toward a
  part elsewhere are 2 dangling power stubs against one Seat.

Totals:
- No cable cell inside any predicted footprint.
- No overlaps with any part other than curved frames and glass: 2 Camera and 2 Monitor Small LCD instances overlap
  the bounding boxes of a curved frame or glass (FrameB, FrameHalfF, GlassB).
- No adjacent cable end off a port, apart from those 2 Seat stubs.
- No direction clashes: no output wired to an output, no input to an input.
- A few data ports touch a Power Router's power port face to face, which is no connection. The evidence file lists
  them as `incompatible_partners`.

## Wiring facts for the generator
- **Video = data cable.** Camera, Night Vision, Zoom, Telescope and Overlay `video` ports are game type data_out, and
  monitor `primary`/`secondary` are data_in.
  - Every corpus hit on them is `SC_DataCable`.
  - Video runs through Data Redirector 3, Data Router 2, Wireless Transmitters and port frames like any data signal.
  - Kind `video` in the JSON keeps the simulator's meaning; `cable` says what to lay.
- **Ports are not only on ±z.**
  - LCD monitors: bottom face (−y).
  - Holographic displays, cameras, Colored Light Controller: back face (−z).
  - Rotational Telescopic Camera: +x side.
  - Red Alert Light: +x side.
  - Use each port's `face`/`facing`. `model.ports()` only derives faces for ±z/±x ports, so it would get the −y
    monitor ports wrong.
- **Several ports share a face.** The Camera Overlay has a 2 × 2 block of inputs plus power and video on its +z face
  (rows y = 0 and y = 1). Port P of the Monitor CRT is next to its video input on the +z face, at mid-height
  (y = 3 of 8).
- **Mount faces** (`mount_faces`, canonical outward normals) are where the part's JointsArea polygons sit, normally the
  face it is built onto: {MOUNTS}.
  - The corpus also shows parts held only by a side face, such as a Camera With Zoom beside a Night Vision Camera.

## Parts
'''

TAIL = r'''
## Settings (per struct; offsets from `schemas.json`, sizes from the PDB)
Each JSON entry lists every non-`_guid`/`_gt` field of its struct with `default`, `meaning`, `offset` and `bytes`.

Decoded beyond the field names:
- **Lever** `_toggle` = the red mode button.
  - 1 = −1..1 mode: `ActionableDoubleLever` clamps to [−1, 1], and `SCTick_DoubleLever` applies a ±0.025 dead zone,
    out = sign(v)·max(0, (|v| − 0.025)/0.975).
  - 0 = 0..1 mode: the output equals `_leverValue`.
  - A generator that wants output v in −1..1 mode should write `_leverValue = sign(v)·(0.025 + 0.975·|v|)`.
- **Large Datameter** `_inputSwitch` is passed as `asFloat` to `CRPText3DString.FromFloatTo8Digit`, i.e. whether
  decimals are shown.
- **Monitor** `_mode` = Knob Mode, 9 steps. The order is taken from the `Monitor_Mode_*` strings.
- **Colored Light** `_knobColor` = `ColoredLight_Col_0..10`.
- **Speaker** `_sound` = `SpeakerSound_0..22`. `_inputMode`: 0 = Play once (plays on a 0 → 1 edge), 1 = Repeat
  (plays again while the input is ≥ 0.5). In `SCTick_Speaker+ActiveJob` a mode value < 0.5 selects the edge
  trigger.
- **Lever corpus check:** the 11 saved levers with a negative `_leverValue` are all in mode 1.
- **Beeper** volume default 0.5. Its `_pitch` byte (offset 25, 0..10, 5 = default) is in the current PDB but not in
  `schemas.json` (older saves), so leave it out.
- **Knob defaults** come from the prefab `EPC_Actionable_Knob` (default value and step count): Beeper/Speaker volume
  0.5, Colored Light intensity 0.7, Camera Overlay size 0.5 = index 2. All others are 0.

## Open questions
1. **TNT Controller, ETA System:** no prefab ships, so the generator must substitute them. The ETA System has code,
   a struct and Localization text but no GameObject. The TNT Controller is demo-only.
2. **Prefab-only parts** (no corpus instance): Lever Horizontal, Horizontal Meter, Speaker, Monitor Large LCD and
   Large Holographic Display. They are derived exactly like the confirmed members of their families. A one-off
   in-game placement test would lift them to high.
3. **Small Holographic Display:** the secondary input (Port B) is never wired in the corpus (2 instances, both
   twins). It follows the Medium Holographic Display layout, which the corpus confirms 3/3.
4. **Enumerations not confirmed from code or saves:**
   - Speaker `_inputMode` polarity (0 = Play once, 1 = Repeat) comes from reading `SCTick_Speaker`; no saved speaker
     exists to check it against;
   - Colored Light channel numbering (101 knob steps; is 0 Manual Mode?) and the controller's 100 steps;
   - the meaning of the Camera Overlay `_alignment`/`_position`/`_graphics` indices and which state of an
     `_inputSwitches` bit shows the row;
   - the LED Text colour list (assumed to be the Colored Light list);
   - the lever's in-game default mode (0..1 is assumed; 243 of 375 saved levers are in −1..1 mode).
5. **Labels:** `_actionableLabel` holds 16 UTF-16 code units with a NUL terminator, so 15 characters
   (`bpformat.with_label`). The game's on-screen limit may be lower.
6. **Not covered here:** `SC_CandyBouquet`, a decoration prefab (8 × 12 × 8, no ports; its 48 corpus records use the
   base `EPC_SpaceshipComponent` struct). `SC_Floodlight` belongs to another group.
'''


def summary():
    parts = {k: v for k, v in D.items() if 'alias_of' not in v}
    sim = [k for k in parts if not k.startswith('SC_')]
    placeable = [k for k, v in parts.items() if v.get('placeable')]
    conf = {c: [k for k in placeable if parts[k]['confidence'] == c] for c in ('high', 'medium', 'low')}
    nope = [parts[k]['name'] for k, v in parts.items() if not v.get('placeable')]
    med = ', '.join(parts[k]['name'] for k in conf['medium'])
    return (f"{len(placeable)} of the {len(parts)} parts in this group are placeable: "
            f"{len([k for k in sim if k in placeable])} simulator types and {len(parts) - len(sim)} extra prefabs. "
            "The simulator's `toggle` and `slider` source types are aliases of Switch and Lever Vertical.\n"
            f"- **High ({len(conf['high'])}):** the corpus confirms the footprint and every port, including the "
            "mirrored twins wherever twins occur.\n"
            f"- **Medium ({len(conf['medium'])}):** {med}. Five have no corpus instance and come from the prefab "
            "alone. The Small Holographic Display has one port the corpus never wires.\n"
            f"- **Not placeable:** {' and '.join(nope)} have no prefab in the game assets (`placeable: false`).\n\n"
            "Video links use **ordinary data cables** (`SC_DataCable`).")


def mounts():
    groups = {}
    names = {(1, 0, 0): '+x', (-1, 0, 0): '-x', (0, 1, 0): '+y', (0, -1, 0): '-y', (0, 0, 1): '+z', (0, 0, -1): '-z'}
    for k, v in D.items():
        if 'alias_of' in v or not v.get('placeable'):
            continue
        key = ' and '.join(names[tuple(n)] for n in v.get('mount_faces', [])) or 'none'
        groups.setdefault(key, []).append(v['name'])
    return '; '.join(f"**{g}**: {', '.join(n)}" for g, n in sorted(groups.items(), key=lambda kv: -len(kv[1])))


def fmt_ports(v, key='ports'):
    out = []
    for n, p in v.get(key, {}).items():
        f = p['facing']
        ax = {(1, 0, 0): '+x', (-1, 0, 0): '-x', (0, 1, 0): '+y', (0, -1, 0): '-y', (0, 0, 1): '+z', (0, 0, -1): '-z'}[tuple(f)]
        out.append(f"`{n}` {tuple(p['cell'])} {ax} {p.get('kind', '')}{'/' + p['dir'] if p.get('dir') else ''}")
    return '; '.join(out) or 'none'


def main():
    rows = ['| key | in-game name | prefab | size w×h×d | twin | struct | corpus n (normal/mirrored) | ports confirmed '
            '(normal / mirrored) | confidence |', '|---|---|---|---|---|---|---|---|---|']
    detail = []
    for k, v in D.items():
        if 'alias_of' in v:
            continue
        c = v.get('corpus', {})
        size = '×'.join(map(str, v['size'])) if v.get('size') else '—'
        st = (v.get('struct') or '—').split('+')[0]
        twin = 'yes' if v.get('mirrored_hash') else 'no'
        n = c.get('instances', 0)
        nm = f"{n} ({c.get('instances_normal', 0)}/{c.get('instances_mirrored', 0)})" if v.get('placeable') else '—'
        pc = (f"{c.get('ports_confirmed')} ({c.get('ports_confirmed_normal') or '–'} / "
              f"{c.get('ports_confirmed_mirrored') or '–'})") if v.get('placeable') else '—'
        conf = v['confidence'] if v.get('placeable') else 'not placeable'
        rows.append(f"| `{k}` | {v['name']} | `{v['prefab']}` | {size} | {twin} | {st} | {nm} | {pc} | {conf} |")
        if not v.get('placeable'):
            detail.append(f"### `{k}`: {v['name']}\nNot placeable. {v['notes']}\n")
            continue
        ev = E.get(k, {})
        lines = [f"### `{k}`: {v['name']} (`{v['prefab']}`, {size}, {conf})",
                 f"- Ports (canonical port cell, outward facing, kind/dir): {fmt_ports(v)}"]
        if v.get('mirrored_ports'):
            lines.append(f"- Twin `{v['prefab']} M` = `{v['mirrored_hash']}`: "
                         + '; '.join(f"`{n}` {tuple(p['cell'])}" for n, p in v['mirrored_ports'].items()))
        if n:
            oris = ev.get('orientations', {})
            lines.append(f"- Corpus: {n} instances in orientations "
                         + ', '.join(f"{kk}: {dict(list(vv.items())[:8])}" for kk, vv in oris.items())
                         + f"; cables inside {c['cables_inside']}; overlaps {c['overlaps']} "
                         f"(+{c['overlaps_with_curved_frame_or_glass_box']} with curved-frame/glass boxes); "
                         f"adjacent cable ends on ports {c['adjacent_cables_opening_toward_part']['on_port']}, "
                         f"elsewhere {c['adjacent_cables_opening_toward_part']['elsewhere'] or 0}; "
                         f"mount face touching {c['mount_face_touching']}.")
            for pn, pe in ev.get('ports', {}).items():
                lines.append(f"  - `{pn}` ({pe['node']}): cable hits {pe['cable_hits'] or 0}, direct contacts "
                             f"{pe['direct_contacts']}, partner types {pe['partner_types'] or '-'}; "
                             f"top partners: {', '.join(pe['top_partners'][:4]) or '-'}")
        else:
            lines.append('- Corpus: no instances. Prefab-derived only.')
        lines.append(f"- Notes: {v['notes']}")
        detail.append('\n'.join(lines) + '\n')
    md = HEAD.replace('{SUMMARY}', summary()).replace('{MOUNTS}', mounts()) + '\n'.join(rows) + '\n\nAliases: `toggle` → `switch` (value → `_buttonPressed`), `slider` → ' \
         '`lever_vertical` (value → `_leverValue`).\n\n## Per-part evidence\n\n' + '\n'.join(detail) + TAIL
    open(os.path.join(HERE, 'controls_displays.md'), 'w', encoding='utf-8').write(md)
    print('wrote controls_displays.md', len(md), 'chars')


if __name__ == '__main__':
    main()
